INSERT INTO Pais(nombre_pais) VALUES('Afganistán');
INSERT INTO Pais(nombre_pais) VALUES('Albania');
INSERT INTO Pais(nombre_pais) VALUES('Alemania');
INSERT INTO Pais(nombre_pais) VALUES('Andorra');
INSERT INTO Pais(nombre_pais) VALUES('Angola');
INSERT INTO Pais(nombre_pais) VALUES('Anguila');
INSERT INTO Pais(nombre_pais) VALUES('Antártida');
INSERT INTO Pais(nombre_pais) VALUES('Antigua y Barbuda');
INSERT INTO Pais(nombre_pais) VALUES('Arabia Saudita');
INSERT INTO Pais(nombre_pais) VALUES('Argelia');
INSERT INTO Pais(nombre_pais) VALUES('Argentina');
INSERT INTO Pais(nombre_pais) VALUES('Armenia');
INSERT INTO Pais(nombre_pais) VALUES('Aruba');
INSERT INTO Pais(nombre_pais) VALUES('Australia');
INSERT INTO Pais(nombre_pais) VALUES('Austria');
INSERT INTO Pais(nombre_pais) VALUES('Azerbaiyán');
INSERT INTO Pais(nombre_pais) VALUES('Bélgica');
INSERT INTO Pais(nombre_pais) VALUES('Bahamas');
INSERT INTO Pais(nombre_pais) VALUES('Bahrein');
INSERT INTO Pais(nombre_pais) VALUES('Bangladesh');
INSERT INTO Pais(nombre_pais) VALUES('Barbados');
INSERT INTO Pais(nombre_pais) VALUES('Belice');
INSERT INTO Pais(nombre_pais) VALUES('Benín');
INSERT INTO Pais(nombre_pais) VALUES('Bhután');
INSERT INTO Pais(nombre_pais) VALUES('Bielorrusia');
INSERT INTO Pais(nombre_pais) VALUES('Birmania');
INSERT INTO Pais(nombre_pais) VALUES('Bolivia');
INSERT INTO Pais(nombre_pais) VALUES('Bosnia y Herzegovina');
INSERT INTO Pais(nombre_pais) VALUES('Botsuana');
INSERT INTO Pais(nombre_pais) VALUES('Brasil');
INSERT INTO Pais(nombre_pais) VALUES('Brunéi');
INSERT INTO Pais(nombre_pais) VALUES('Bulgaria');
INSERT INTO Pais(nombre_pais) VALUES('Burkina Faso');
INSERT INTO Pais(nombre_pais) VALUES('Burundi');
INSERT INTO Pais(nombre_pais) VALUES('Cabo Verde');
INSERT INTO Pais(nombre_pais) VALUES('Camboya');
INSERT INTO Pais(nombre_pais) VALUES('Camerún');
INSERT INTO Pais(nombre_pais) VALUES('Canadá');
INSERT INTO Pais(nombre_pais) VALUES('Chad');
INSERT INTO Pais(nombre_pais) VALUES('Chile');
INSERT INTO Pais(nombre_pais) VALUES('China');
INSERT INTO Pais(nombre_pais) VALUES('Chipre');
INSERT INTO Pais(nombre_pais) VALUES('Ciudad del Vaticano');
INSERT INTO Pais(nombre_pais) VALUES('Colombia');
INSERT INTO Pais(nombre_pais) VALUES('Comoras');
INSERT INTO Pais(nombre_pais) VALUES('República del Congo');
INSERT INTO Pais(nombre_pais) VALUES('República Democrática del Congo');
INSERT INTO Pais(nombre_pais) VALUES('Corea del Norte');
INSERT INTO Pais(nombre_pais) VALUES('Corea del Sur');
INSERT INTO Pais(nombre_pais) VALUES('Costa de Marfil');
INSERT INTO Pais(nombre_pais) VALUES('Costa Rica');
INSERT INTO Pais(nombre_pais) VALUES('Croacia');
INSERT INTO Pais(nombre_pais) VALUES('Cuba');
INSERT INTO Pais(nombre_pais) VALUES('Curazao');
INSERT INTO Pais(nombre_pais) VALUES('Dinamarca');
INSERT INTO Pais(nombre_pais) VALUES('Dominica');
INSERT INTO Pais(nombre_pais) VALUES('Ecuador');
INSERT INTO Pais(nombre_pais) VALUES('Egipto');
INSERT INTO Pais(nombre_pais) VALUES('El Salvador');
INSERT INTO Pais(nombre_pais) VALUES('Emiratos Árabes Unidos');
INSERT INTO Pais(nombre_pais) VALUES('Eritrea');
INSERT INTO Pais(nombre_pais) VALUES('Eslovaquia');
INSERT INTO Pais(nombre_pais) VALUES('Eslovenia');
INSERT INTO Pais(nombre_pais) VALUES('España');
INSERT INTO Pais(nombre_pais) VALUES('Estados Unidos de América');
INSERT INTO Pais(nombre_pais) VALUES('Estonia');
INSERT INTO Pais(nombre_pais) VALUES('Etiopía');
INSERT INTO Pais(nombre_pais) VALUES('Filipinas');
INSERT INTO Pais(nombre_pais) VALUES('Finlandia');
INSERT INTO Pais(nombre_pais) VALUES('Fiyi');
INSERT INTO Pais(nombre_pais) VALUES('Francia');
INSERT INTO Pais(nombre_pais) VALUES('Gabón');
INSERT INTO Pais(nombre_pais) VALUES('Gambia');
INSERT INTO Pais(nombre_pais) VALUES('Georgia');
INSERT INTO Pais(nombre_pais) VALUES('Ghana');
INSERT INTO Pais(nombre_pais) VALUES('Gibraltar');
INSERT INTO Pais(nombre_pais) VALUES('Granada');
INSERT INTO Pais(nombre_pais) VALUES('Grecia');
INSERT INTO Pais(nombre_pais) VALUES('Groenlandia');
INSERT INTO Pais(nombre_pais) VALUES('Guadalupe');
INSERT INTO Pais(nombre_pais) VALUES('Guam');
INSERT INTO Pais(nombre_pais) VALUES('Guatemala');
INSERT INTO Pais(nombre_pais) VALUES('Guayana Francesa');
INSERT INTO Pais(nombre_pais) VALUES('Guernsey');
INSERT INTO Pais(nombre_pais) VALUES('Guinea');
INSERT INTO Pais(nombre_pais) VALUES('Guinea Ecuatorial');
INSERT INTO Pais(nombre_pais) VALUES('Guinea-Bissau');
INSERT INTO Pais(nombre_pais) VALUES('Guyana');
INSERT INTO Pais(nombre_pais) VALUES('Haití');
INSERT INTO Pais(nombre_pais) VALUES('Honduras');
INSERT INTO Pais(nombre_pais) VALUES('Hong kong');
INSERT INTO Pais(nombre_pais) VALUES('Hungría');
INSERT INTO Pais(nombre_pais) VALUES('India');
INSERT INTO Pais(nombre_pais) VALUES('Indonesia');
INSERT INTO Pais(nombre_pais) VALUES('Irán');
INSERT INTO Pais(nombre_pais) VALUES('Irak');
INSERT INTO Pais(nombre_pais) VALUES('Irlanda');
INSERT INTO Pais(nombre_pais) VALUES('Isla Bouvet');
INSERT INTO Pais(nombre_pais) VALUES('Isla de Man');
INSERT INTO Pais(nombre_pais) VALUES('Isla de Navidad');
INSERT INTO Pais(nombre_pais) VALUES('Isla Norfolk');
INSERT INTO Pais(nombre_pais) VALUES('Islandia');
INSERT INTO Pais(nombre_pais) VALUES('Islas Bermudas');
INSERT INTO Pais(nombre_pais) VALUES('Islas Caimán');
INSERT INTO Pais(nombre_pais) VALUES('Islas Cocos (Keeling)');
INSERT INTO Pais(nombre_pais) VALUES('Islas Cook');
INSERT INTO Pais(nombre_pais) VALUES('Islas de Åland');
INSERT INTO Pais(nombre_pais) VALUES('Islas Feroe');
INSERT INTO Pais(nombre_pais) VALUES('Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO Pais(nombre_pais) VALUES('Islas Heard y McDonald');
INSERT INTO Pais(nombre_pais) VALUES('Islas Maldivas');
INSERT INTO Pais(nombre_pais) VALUES('Islas Malvinas');
INSERT INTO Pais(nombre_pais) VALUES('Islas Marianas del Norte');
INSERT INTO Pais(nombre_pais) VALUES('Islas Marshall');
INSERT INTO Pais(nombre_pais) VALUES('Islas Pitcairn');
INSERT INTO Pais(nombre_pais) VALUES('Islas Salomón');
INSERT INTO Pais(nombre_pais) VALUES('Islas Turcas y Caicos');
INSERT INTO Pais(nombre_pais) VALUES('Islas Ultramarinas Menores de Estados Unidos');
INSERT INTO Pais(nombre_pais) VALUES('Islas Vírgenes Británicas');
INSERT INTO Pais(nombre_pais) VALUES('Islas Vírgenes de los Estados Unidos');
INSERT INTO Pais(nombre_pais) VALUES('Israel');
INSERT INTO Pais(nombre_pais) VALUES('Italia');
INSERT INTO Pais(nombre_pais) VALUES('Jamaica');
INSERT INTO Pais(nombre_pais) VALUES('Japón');
INSERT INTO Pais(nombre_pais) VALUES('Jersey');
INSERT INTO Pais(nombre_pais) VALUES('Jordania');
INSERT INTO Pais(nombre_pais) VALUES('Kazajistán');
INSERT INTO Pais(nombre_pais) VALUES('Kenia');
INSERT INTO Pais(nombre_pais) VALUES('Kirguistán');
INSERT INTO Pais(nombre_pais) VALUES('Kiribati');
INSERT INTO Pais(nombre_pais) VALUES('Kuwait');
INSERT INTO Pais(nombre_pais) VALUES('Líbano');
INSERT INTO Pais(nombre_pais) VALUES('Laos');
INSERT INTO Pais(nombre_pais) VALUES('Lesoto');
INSERT INTO Pais(nombre_pais) VALUES('Letonia');
INSERT INTO Pais(nombre_pais) VALUES('Liberia');
INSERT INTO Pais(nombre_pais) VALUES('Libia');
INSERT INTO Pais(nombre_pais) VALUES('Liechtenstein');
INSERT INTO Pais(nombre_pais) VALUES('Lituania');
INSERT INTO Pais(nombre_pais) VALUES('Luxemburgo');
INSERT INTO Pais(nombre_pais) VALUES('México');
INSERT INTO Pais(nombre_pais) VALUES('Mónaco');
INSERT INTO Pais(nombre_pais) VALUES('Macao');
INSERT INTO Pais(nombre_pais) VALUES('Macedônia');
INSERT INTO Pais(nombre_pais) VALUES('Madagascar');
INSERT INTO Pais(nombre_pais) VALUES('Malasia');
INSERT INTO Pais(nombre_pais) VALUES('Malawi');
INSERT INTO Pais(nombre_pais) VALUES('Mali');
INSERT INTO Pais(nombre_pais) VALUES('Malta');
INSERT INTO Pais(nombre_pais) VALUES('Marruecos');
INSERT INTO Pais(nombre_pais) VALUES('Martinica');
INSERT INTO Pais(nombre_pais) VALUES('Mauricio');
INSERT INTO Pais(nombre_pais) VALUES('Mauritania');
INSERT INTO Pais(nombre_pais) VALUES('Mayotte');
INSERT INTO Pais(nombre_pais) VALUES('Micronesia');
INSERT INTO Pais(nombre_pais) VALUES('Moldavia');
INSERT INTO Pais(nombre_pais) VALUES('Mongolia');
INSERT INTO Pais(nombre_pais) VALUES('Montenegro');
INSERT INTO Pais(nombre_pais) VALUES('Montserrat');
INSERT INTO Pais(nombre_pais) VALUES('Mozambique');
INSERT INTO Pais(nombre_pais) VALUES('Namibia');
INSERT INTO Pais(nombre_pais) VALUES('Nauru');
INSERT INTO Pais(nombre_pais) VALUES('Nepal');
INSERT INTO Pais(nombre_pais) VALUES('Nicaragua');
INSERT INTO Pais(nombre_pais) VALUES('Niger');
INSERT INTO Pais(nombre_pais) VALUES('Nigeria');
INSERT INTO Pais(nombre_pais) VALUES('Niue');
INSERT INTO Pais(nombre_pais) VALUES('Noruega');
INSERT INTO Pais(nombre_pais) VALUES('Nueva Caledonia');
INSERT INTO Pais(nombre_pais) VALUES('Nueva Zelanda');
INSERT INTO Pais(nombre_pais) VALUES('Omán');
INSERT INTO Pais(nombre_pais) VALUES('Países Bajos');
INSERT INTO Pais(nombre_pais) VALUES('Pakistán');
INSERT INTO Pais(nombre_pais) VALUES('Palau');
INSERT INTO Pais(nombre_pais) VALUES('Palestina');
INSERT INTO Pais(nombre_pais) VALUES('Panamá');
INSERT INTO Pais(nombre_pais) VALUES('Papúa Nueva Guinea');
INSERT INTO Pais(nombre_pais) VALUES('Paraguay');
INSERT INTO Pais(nombre_pais) VALUES('Perú');
INSERT INTO Pais(nombre_pais) VALUES('Polinesia Francesa');
INSERT INTO Pais(nombre_pais) VALUES('Polonia');
INSERT INTO Pais(nombre_pais) VALUES('Portugal');
INSERT INTO Pais(nombre_pais) VALUES('Puerto Rico');
INSERT INTO Pais(nombre_pais) VALUES('Qatar');
INSERT INTO Pais(nombre_pais) VALUES('Reino Unido');
INSERT INTO Pais(nombre_pais) VALUES('República Centroafricana');
INSERT INTO Pais(nombre_pais) VALUES('República Checa');
INSERT INTO Pais(nombre_pais) VALUES('República Dominicana');
INSERT INTO Pais(nombre_pais) VALUES('República de Sudán del Sur');
INSERT INTO Pais(nombre_pais) VALUES('Reunión');
INSERT INTO Pais(nombre_pais) VALUES('Ruanda');
INSERT INTO Pais(nombre_pais) VALUES('Rumanía');
INSERT INTO Pais(nombre_pais) VALUES('Rusia');
INSERT INTO Pais(nombre_pais) VALUES('Sahara Occidental');
INSERT INTO Pais(nombre_pais) VALUES('Samoa');
INSERT INTO Pais(nombre_pais) VALUES('Samoa Americana');
INSERT INTO Pais(nombre_pais) VALUES('San Bartolomé');
INSERT INTO Pais(nombre_pais) VALUES('San Cristóbal y Nieves');
INSERT INTO Pais(nombre_pais) VALUES('San Marino');
INSERT INTO Pais(nombre_pais) VALUES('San Martín (Francia)');
INSERT INTO Pais(nombre_pais) VALUES('San Pedro y Miquelón');
INSERT INTO Pais(nombre_pais) VALUES('San Vicente y las Granadinas');
INSERT INTO Pais(nombre_pais) VALUES('Santa Elena');
INSERT INTO Pais(nombre_pais) VALUES('Santa Lucía');
INSERT INTO Pais(nombre_pais) VALUES('Santo Tomé y Príncipe');
INSERT INTO Pais(nombre_pais) VALUES('Senegal');
INSERT INTO Pais(nombre_pais) VALUES('Serbia');
INSERT INTO Pais(nombre_pais) VALUES('Seychelles');
INSERT INTO Pais(nombre_pais) VALUES('Sierra Leona');
INSERT INTO Pais(nombre_pais) VALUES('Singapur');
INSERT INTO Pais(nombre_pais) VALUES('Sint Maarten');
INSERT INTO Pais(nombre_pais) VALUES('Siria');
INSERT INTO Pais(nombre_pais) VALUES('Somalia');
INSERT INTO Pais(nombre_pais) VALUES('Sri lanka');
INSERT INTO Pais(nombre_pais) VALUES('Sudáfrica');
INSERT INTO Pais(nombre_pais) VALUES('Sudán');
INSERT INTO Pais(nombre_pais) VALUES('Suecia');
INSERT INTO Pais(nombre_pais) VALUES('Suiza');
INSERT INTO Pais(nombre_pais) VALUES('Surinám');
INSERT INTO Pais(nombre_pais) VALUES('Svalbard y Jan Mayen');
INSERT INTO Pais(nombre_pais) VALUES('Swazilandia');
INSERT INTO Pais(nombre_pais) VALUES('Tayikistán');
INSERT INTO Pais(nombre_pais) VALUES('Tailandia');
INSERT INTO Pais(nombre_pais) VALUES('Taiwán');
INSERT INTO Pais(nombre_pais) VALUES('Tanzania');
INSERT INTO Pais(nombre_pais) VALUES('Territorio Británico del Océano Índico');
INSERT INTO Pais(nombre_pais) VALUES('Territorios Australes y Antárticas Franceses');
INSERT INTO Pais(nombre_pais) VALUES('Timor Oriental');
INSERT INTO Pais(nombre_pais) VALUES('Togo');
INSERT INTO Pais(nombre_pais) VALUES('Tokelau');
INSERT INTO Pais(nombre_pais) VALUES('Tonga');
INSERT INTO Pais(nombre_pais) VALUES('Trinidad y Tobago');
INSERT INTO Pais(nombre_pais) VALUES('Tunez');
INSERT INTO Pais(nombre_pais) VALUES('Turkmenistán');
INSERT INTO Pais(nombre_pais) VALUES('Turquía');
INSERT INTO Pais(nombre_pais) VALUES('Tuvalu');
INSERT INTO Pais(nombre_pais) VALUES('Ucrania');
INSERT INTO Pais(nombre_pais) VALUES('Uganda');
INSERT INTO Pais(nombre_pais) VALUES('Uruguay');
INSERT INTO Pais(nombre_pais) VALUES('Uzbekistán');
INSERT INTO Pais(nombre_pais) VALUES('Vanuatu');
INSERT INTO Pais(nombre_pais) VALUES('Venezuela');
INSERT INTO Pais(nombre_pais) VALUES('Vietnam');
INSERT INTO Pais(nombre_pais) VALUES('Wallis y Futuna');
INSERT INTO Pais(nombre_pais) VALUES('Yemen');
INSERT INTO Pais(nombre_pais) VALUES('Yibuti');
INSERT INTO Pais(nombre_pais) VALUES('Zambia');
INSERT INTO Pais(nombre_pais) VALUES('Zimbabue');